---
name: "build images"

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
    tags:
      - "**"
jobs:
  docker:
    strategy:
      matrix:
        include:
        - CUDA_VER: 10.2
          UBUNTU_VER: 18.04
          PLATFORMS: linux/amd64
        - CUDA_VER: 11.3.1
          UBUNTU_VER: 20.04
          PYTORCH_EXTRA_IDX_URL: https://download.pytorch.org/whl/cu113
          PLATFORMS: linux/amd64,linux/arm64
        - CUDA_VER: 11.6.1
          UBUNTU_VER: 20.04
          PYTORCH_EXTRA_IDX_URL: https://download.pytorch.org/whl/cu116
          PLATFORMS: linux/amd64,linux/arm64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            walkerlab/pytorch
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            UBUNTU_VER=${{ matrix.UBUNTU_VER }}
            CUDA_VER=${{ matrix.CUDA_VER }}
            PYTORCH_EXTRA_IDX_URL=${{ matrix.PYTORCH_EXTRA_IDX_URL }}
          file: ./Dockerfile
          platforms: ${{ matrix.PLATFORMS }}
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
