---
name: "build images"

on:
  pull_request:
    types:
      - opened
  push:
    branches:
      - main
    tags:
      - "**"
jobs:
  docker:
    strategy:
      matrix:
        UBUNTU_VER: [20.04, 22.04]
        include:
        - CUDA_VER: 10.2.0
        - CUDA_VER: 11.3.1
          PYTORCH_EXTRA_IDX_URL: https://download.pytorch.org/whl/cu113
        - CUDA_VER: 11.6.0
          PYTORCH_EXTRA_IDX_URL: https://download.pytorch.org/whl/cu116
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            walkerlab/pytorch
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          build-args: |
            --build-arg UBUNTU_VER=${{ UBUNTU_VER }}
            --build-arg CUDA_VER=${{ CUDA_VER }}
            --build-arg PYTORCH_EXTRA_IDX_URL=${{ PYTORCH_EXTRA_IDX_URL }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
